name: Publish

permissions: write-all

on:
  push:
    branches:
      - main
    paths:
      - 'YOUR_PACKAGE_NAME/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
          
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
          
      - name: Install dependencies
        run: |
          pipenv install -- dev
          
      - name: Bump version and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv run bump2version patch --commit --tag
          git push origin --tags
          
      - name: Create source distribution
        run: |
          python setup.py sdist
          
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
